apiVersion: apps/v1
kind: Deployment
metadata:
  name: merak-agent
  labels:
    app: merak-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merak-agent
  template:
    metadata:
      labels:
        app: merak-agent
    spec:
      imagePullSecrets:
        - name: ""
      containers:
        - name: agent
          image: merakhq/merak:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args: ["merak agent kubernetes start"]
          env:
            - name: merak__CLOUD__AGENT__AUTH_TOKEN
              value: ""
            - name: merak__CLOUD__API
              value: "https://api.merak.io"
            - name: NAMESPACE
              value: "default"
            - name: IMAGE_PULL_SECRETS
              value: ""
            - name: merak__CLOUD__AGENT__LABELS
              value: "[]"
            - name: JOB_MEM_REQUEST
              value: ""
            - name: JOB_MEM_LIMIT
              value: ""
            - name: JOB_CPU_REQUEST
              value: ""
            - name: JOB_CPU_LIMIT
              value: ""
            - name: IMAGE_PULL_POLICY
              value: ""
            - name: SERVICE_ACCOUNT_NAME
              value: ""
            - name: merak__BACKEND
              value: "cloud"
            - name: merak__CLOUD__AGENT__AGENT_ADDRESS
              value: "http://:8080"
            - name: merak__CLOUD__API_KEY
              value: ""
            - name: merak__CLOUD__TENANT_ID
              value: ""
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 40
            failureThreshold: 2
