apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: merak-agent-rbac
rules:
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events", "pods"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: merak-agent-rbac
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: merak-agent-rbac
  apiGroup: rbac.authorization.k8s.io
